---
title: "p8105_hw2_jys2136"
author: "Jocelyn Sun"
date: "10/7/2021"
output: github_document
---

We will be using the following packages for this assignment:
```{r, loading_packages, message = FALSE}

library(tidyverse)
library(readxl)

```

# Problem 1

## Mr. Trash Wheel

### Importing and Cleaning Mr. Trash Wheel
```{r, mr_trash_wheel, message = FALSE}

trash_df = 
  read_excel("data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
              sheet = "Mr. Trash Wheel",
              skip = 1) %>%
  janitor::clean_names() %>%
  select("dumpster":"homes_powered") %>%
  drop_na("dumpster") %>%
  mutate(sports_balls = round(sports_balls, digits = 0))

```


### Precipitation Data
```{r, precipitation, message = FALSE}
#Importing & cleaning 2018 Precipitation Data:

precip_2018 = 
  read_excel("data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
              sheet = "2018 Precipitation",
              skip = 1) %>%
  janitor::clean_names() %>%
  drop_na("month") %>%
  mutate(year = 2018)

  
#Importing & cleaning 2019 Precipitation Data:

precip_2019 = 
  read_excel("data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
              sheet = "2019 Precipitation",
              skip = 1) %>%
  janitor::clean_names() %>%
  drop_na(c("month", "total")) %>%
  mutate(year = 2019)

```


### Combining Precipitation Data
```{r, combining_precipitation, message = FALSE}

precip_all = 
  bind_rows(precip_2018, precip_2019) %>%
  mutate(month = month.name[as.numeric(month)])

```


# Problem 2

## FiveThirtyEight Data

### Politicians Dataset
```{r, politicians_data, message = FALSE}

politicians_df =
  read_csv("data/fivethirtyeight_datasets/pols-month.csv") %>%
  separate("mon", into = c("year", "month", "day")) %>%
  mutate(
    month = month.name[as.numeric(month)],
    year = as.numeric(year),
    president = recode(prez_dem, "0" = "gop", "1" = "dem")) %>%
  select(-day, -prez_dem, -prez_gop)

```


### S&P Dataset
```{r, snp_data, message = FALSE}

snp_df = 
  read_csv("data/fivethirtyeight_datasets/snp.csv") %>%
  separate("date", into = c("month", "day", "year")) %>%
  mutate(
    month = month.name[as.numeric(month)],
    year = as.numeric(year),
    year = if_else(year <= 15, year + 2000, year + 1900),
    day = as.numeric(day)
  ) %>%
  select(year, month, close, -day)
  
```


### Unemployment Dataset
```{r, unemployment_data, message = FALSE}

unemploy_df = 
  read_csv("data/fivethirtyeight_datasets/unemployment.csv") %>%
  rename(
    "January" = "Jan", 
    "February" = "Feb", 
    "March" = "Mar",
    "April" = "Apr",
    "June" = "Jun",
    "July" = "Jul",
    "August" = "Aug",
    "September" = "Sep",
    "October" = "Oct",
    "November" = "Nov",
    "December" = "Dec") %>%
  pivot_longer(
    "January":"December",
    names_to = "month",
    values_to = "umemployment") %>%
  janitor::clean_names()

```

### Combining FiveThirtyEight Data
```{r, merging_FiveThirtyEight_data, message = FALSE}

combined_df = 
  left_join(politicians_df, snp_df, unemploy_df, 
            by = c("year","month"))

```



# Problem 3

```{r}


```








